# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpineSeg_fix.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.trainData12 = QtWidgets.QPushButton(self.centralwidget)
        self.trainData12.setGeometry(QtCore.QRect(20, 170, 91, 23))
        self.trainData12.setObjectName("trainData12")
        self.trainData13 = QtWidgets.QPushButton(self.centralwidget)
        self.trainData13.setGeometry(QtCore.QRect(20, 210, 91, 21))
        self.trainData13.setObjectName("trainData13")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(1000, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.number_GT = QtWidgets.QLabel(self.centralwidget)
        self.number_GT.setGeometry(QtCore.QRect(1000, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.number_GT.setFont(font)
        self.number_GT.setObjectName("number_GT")
        self.Detect_number = QtWidgets.QLabel(self.centralwidget)
        self.Detect_number.setGeometry(QtCore.QRect(1000, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Detect_number.setFont(font)
        self.Detect_number.setObjectName("Detect_number")
        self.trainData23 = QtWidgets.QPushButton(self.centralwidget)
        self.trainData23.setGeometry(QtCore.QRect(20, 240, 91, 23))
        self.trainData23.setObjectName("trainData23")
        self.InputIMG = QtWidgets.QLabel(self.centralwidget)
        self.InputIMG.setGeometry(QtCore.QRect(160, 100, 250, 600))
        self.InputIMG.setObjectName("InputIMG")
        self.ImgDetect = QtWidgets.QLabel(self.centralwidget)
        self.ImgDetect.setGeometry(QtCore.QRect(420, 100, 250, 600))
        self.ImgDetect.setObjectName("ImgDetect")
        self.SegmanetIMG = QtWidgets.QLabel(self.centralwidget)
        self.SegmanetIMG.setGeometry(QtCore.QRect(690, 100, 250, 600))
        self.SegmanetIMG.setObjectName("SegmanetIMG")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 710, 47, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 710, 47, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 710, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1000, 150, 47, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1000, 190, 47, 12))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1000, 220, 47, 12))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1000, 250, 47, 12))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1000, 290, 47, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1000, 490, 47, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1000, 520, 47, 12))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1000, 330, 47, 12))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1000, 390, 47, 12))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1000, 430, 47, 12))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1000, 460, 47, 12))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1000, 360, 47, 12))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1000, 550, 47, 12))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1000, 580, 47, 12))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1000, 610, 47, 12))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1000, 640, 47, 12))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1000, 670, 47, 12))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1000, 690, 47, 12))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1000, 710, 47, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(1000, 740, 47, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(1000, 770, 47, 12))
        self.label_24.setObjectName("label_24")
        self.V0 = QtWidgets.QLabel(self.centralwidget)
        self.V0.setGeometry(QtCore.QRect(1050, 190, 71, 16))
        self.V0.setText("")
        self.V0.setObjectName("V0")
        self.V1 = QtWidgets.QLabel(self.centralwidget)
        self.V1.setGeometry(QtCore.QRect(1050, 220, 71, 16))
        self.V1.setText("")
        self.V1.setObjectName("V1")
        self.V2 = QtWidgets.QLabel(self.centralwidget)
        self.V2.setGeometry(QtCore.QRect(1050, 250, 71, 16))
        self.V2.setText("")
        self.V2.setObjectName("V2")
        self.V3 = QtWidgets.QLabel(self.centralwidget)
        self.V3.setGeometry(QtCore.QRect(1050, 290, 61, 16))
        self.V3.setText("")
        self.V3.setObjectName("V3")
        self.V4 = QtWidgets.QLabel(self.centralwidget)
        self.V4.setGeometry(QtCore.QRect(1050, 330, 71, 16))
        self.V4.setText("")
        self.V4.setObjectName("V4")
        self.V5 = QtWidgets.QLabel(self.centralwidget)
        self.V5.setGeometry(QtCore.QRect(1050, 360, 71, 16))
        self.V5.setText("")
        self.V5.setObjectName("V5")
        self.V6 = QtWidgets.QLabel(self.centralwidget)
        self.V6.setGeometry(QtCore.QRect(1050, 390, 81, 16))
        self.V6.setText("")
        self.V6.setObjectName("V6")
        self.V7 = QtWidgets.QLabel(self.centralwidget)
        self.V7.setGeometry(QtCore.QRect(1050, 430, 71, 16))
        self.V7.setText("")
        self.V7.setObjectName("V7")
        self.V8 = QtWidgets.QLabel(self.centralwidget)
        self.V8.setGeometry(QtCore.QRect(1050, 460, 81, 16))
        self.V8.setText("")
        self.V8.setObjectName("V8")
        self.V9 = QtWidgets.QLabel(self.centralwidget)
        self.V9.setGeometry(QtCore.QRect(1050, 490, 81, 16))
        self.V9.setText("")
        self.V9.setObjectName("V9")
        self.V10 = QtWidgets.QLabel(self.centralwidget)
        self.V10.setGeometry(QtCore.QRect(1050, 520, 81, 16))
        self.V10.setText("")
        self.V10.setObjectName("V10")
        self.V11 = QtWidgets.QLabel(self.centralwidget)
        self.V11.setGeometry(QtCore.QRect(1050, 550, 81, 16))
        self.V11.setText("")
        self.V11.setObjectName("V11")
        self.V12 = QtWidgets.QLabel(self.centralwidget)
        self.V12.setGeometry(QtCore.QRect(1050, 580, 81, 16))
        self.V12.setText("")
        self.V12.setObjectName("V12")
        self.V13 = QtWidgets.QLabel(self.centralwidget)
        self.V13.setGeometry(QtCore.QRect(1050, 610, 71, 16))
        self.V13.setText("")
        self.V13.setObjectName("V13")
        self.V14 = QtWidgets.QLabel(self.centralwidget)
        self.V14.setGeometry(QtCore.QRect(1050, 640, 71, 21))
        self.V14.setText("")
        self.V14.setObjectName("V14")
        self.V15 = QtWidgets.QLabel(self.centralwidget)
        self.V15.setGeometry(QtCore.QRect(1050, 670, 71, 16))
        self.V15.setText("")
        self.V15.setObjectName("V15")
        self.V16 = QtWidgets.QLabel(self.centralwidget)
        self.V16.setGeometry(QtCore.QRect(1050, 690, 61, 16))
        self.V16.setText("")
        self.V16.setObjectName("V16")
        self.V17 = QtWidgets.QLabel(self.centralwidget)
        self.V17.setGeometry(QtCore.QRect(1050, 710, 61, 16))
        self.V17.setText("")
        self.V17.setObjectName("V17")
        self.V18 = QtWidgets.QLabel(self.centralwidget)
        self.V18.setGeometry(QtCore.QRect(1050, 740, 61, 16))
        self.V18.setText("")
        self.V18.setObjectName("V18")
        self.V19 = QtWidgets.QLabel(self.centralwidget)
        self.V19.setGeometry(QtCore.QRect(1050, 770, 71, 16))
        self.V19.setText("")
        self.V19.setObjectName("V19")
        self.LoadImg = QtWidgets.QPushButton(self.centralwidget)
        self.LoadImg.setGeometry(QtCore.QRect(30, 700, 81, 21))
        self.LoadImg.setObjectName("LoadImg")
        self.Predict = QtWidgets.QPushButton(self.centralwidget)
        self.Predict.setGeometry(QtCore.QRect(30, 730, 81, 23))
        self.Predict.setObjectName("Predict")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(980, 790, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.average = QtWidgets.QLabel(self.centralwidget)
        self.average.setGeometry(QtCore.QRect(1050, 792, 91, 31))
        self.average.setText("")
        self.average.setObjectName("average")
        self.loadmodel = QtWidgets.QPushButton(self.centralwidget)
        self.loadmodel.setGeometry(QtCore.QRect(30, 672, 81, 21))
        self.loadmodel.setObjectName("loadmodel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.trainData12.setText(_translate("MainWindow", "TrainData:1、2"))
        self.trainData13.setText(_translate("MainWindow", "TrainData:1、3"))
        self.label1.setText(_translate("MainWindow", "Number of vertebra:"))
        self.number_GT.setText(_translate("MainWindow", "GT:"))
        self.Detect_number.setText(_translate("MainWindow", "Detected:"))
        self.trainData23.setText(_translate("MainWindow", "TrainData:2、3"))
        self.InputIMG.setText(_translate("MainWindow", "InputIMG"))
        self.ImgDetect.setText(_translate("MainWindow", "DetectIMG"))
        self.SegmanetIMG.setText(_translate("MainWindow", "ResultIMG"))
        self.label.setText(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Detected"))
        self.label_3.setText(_translate("MainWindow", "Segmentation"))
        self.label_4.setText(_translate("MainWindow", "DC:"))
        self.label_7.setText(_translate("MainWindow", "V0:"))
        self.label_6.setText(_translate("MainWindow", "V1:"))
        self.label_5.setText(_translate("MainWindow", "V2:"))
        self.label_8.setText(_translate("MainWindow", "V3:"))
        self.label_9.setText(_translate("MainWindow", "V9:"))
        self.label_10.setText(_translate("MainWindow", "V10:"))
        self.label_11.setText(_translate("MainWindow", "V4:"))
        self.label_12.setText(_translate("MainWindow", "V6:"))
        self.label_13.setText(_translate("MainWindow", "V7:"))
        self.label_14.setText(_translate("MainWindow", "V8:"))
        self.label_15.setText(_translate("MainWindow", "V5:"))
        self.label_16.setText(_translate("MainWindow", "V11:"))
        self.label_17.setText(_translate("MainWindow", "V12:"))
        self.label_18.setText(_translate("MainWindow", "V13:"))
        self.label_19.setText(_translate("MainWindow", "V14:"))
        self.label_20.setText(_translate("MainWindow", "V15:"))
        self.label_21.setText(_translate("MainWindow", "V16:"))
        self.label_22.setText(_translate("MainWindow", "V17:"))
        self.label_23.setText(_translate("MainWindow", "V18:"))
        self.label_24.setText(_translate("MainWindow", "V19:"))
        self.LoadImg.setText(_translate("MainWindow", "LoadImg"))
        self.Predict.setText(_translate("MainWindow", "Predict"))
        self.label_25.setText(_translate("MainWindow", "Average:"))
        self.loadmodel.setText(_translate("MainWindow", "LoadModel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

