wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1636641206
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.6.13
      5: 0.12.6
      8:
      - 1
      - 3
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 5
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 0.001
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
